export const projectsData = [
  {
    id: 1,
    title: "Market Research Analysis",
    client: "Acme Corporation",
    startDate: "2023-01-15",
    endDate: "2023-03-20",
    status: "completed",
    description: "Comprehensive market analysis for new product launch",
    consultants: ["Alex Morgan", "Sarah Chen"],
    milestones: [
      { title: "Initial Research", date: "2023-01-20", completed: true },
      { title: "Competitor Analysis", date: "2023-02-10", completed: true },
      { title: "Final Report", date: "2023-03-15", completed: true },
    ],
  },
  {
    id: 2,
    title: "Digital Transformation Strategy",
    client: "TechVision Inc",
    startDate: "2023-02-10",
    endDate: "2023-06-30",
    status: "active",
    description: "Enterprise-wide digital transformation initiative",
    consultants: ["James Wilson", "Maria Rodriguez", "David Kim"],
    milestones: [
      { title: "Discovery Phase", date: "2023-02-20", completed: true },
      { title: "Strategy Development", date: "2023-04-15", completed: true },
      { title: "Implementation Plan", date: "2023-05-30", completed: false },
      { title: "Final Handoff", date: "2023-06-25", completed: false },
    ],
  },
  {
    id: 3,
    title: "Supply Chain Optimization",
    client: "Global Logistics Ltd",
    startDate: "2023-03-05",
    endDate: "2023-07-15",
    status: "active",
    description: "End-to-end supply chain efficiency improvement",
    consultants: ["Robert Chen", "Emma Davis"],
    milestones: [
      { title: "Current State Assessment", date: "2023-03-15", completed: true },
      { title: "Process Redesign", date: "2023-05-01", completed: true },
      { title: "Pilot Implementation", date: "2023-06-10", completed: false },
      { title: "Performance Measurement", date: "2023-07-10", completed: false },
    ],
  },
  {
    id: 4,
    title: "Brand Repositioning",
    client: "Luxury Brands Co",
    startDate: "2023-04-10",
    endDate: "2023-08-20",
    status: "at-risk",
    description: "Strategic brand repositioning for luxury market segment",
    consultants: ["Sophia Martinez", "Thomas Johnson"],
    milestones: [
      { title: "Market Research", date: "2023-04-25", completed: true },
      { title: "Brand Strategy", date: "2023-06-01", completed: false },
      { title: "Creative Development", date: "2023-07-15", completed: false },
      { title: "Launch Plan", date: "2023-08-10", completed: false },
    ],
  },
  {
    id: 5,
    title: "Financial Systems Upgrade",
    client: "First National Bank",
    startDate: "2023-05-15",
    endDate: "2023-11-30",
    status: "planned",
    description: "Modernization of core financial systems",
    consultants: ["Michael Chang", "Jennifer Smith", "Kevin Brown"],
    milestones: [
      { title: "Requirements Gathering", date: "2023-06-15", completed: false },
      { title: "Vendor Selection", date: "2023-07-30", completed: false },
      { title: "System Implementation", date: "2023-10-15", completed: false },
      { title: "User Training", date: "2023-11-15", completed: false },
    ],
  },
]

