export const projectsData = [
  {
    id: 1,
    title: "Market Research Analysis",
    client: "Acme Corporation",
    startDate: "2023-01-15",
    endDate: "2023-03-20",
    status: "completed",
    description: "Comprehensive market analysis for new product launch",
    consultants: ["Alex Morgan", "Sarah Chen"],
  },
  {
    id: 2,
    title: "Digital Transformation Strategy",
    client: "TechVision Inc",
    startDate: "2023-02-10",
    endDate: "2023-06-30",
    status: "active",
    description: "Enterprise-wide digital transformation initiative",
    consultants: ["James Wilson", "Maria Rodriguez", "David Kim"],
  },
  {
    id: 3,
    title: "Supply Chain Optimization",
    client: "Global Logistics Ltd",
    startDate: "2023-03-05",
    endDate: "2023-07-15",
    status: "active",
    description: "End-to-end supply chain efficiency improvement",
    consultants: ["Robert Chen", "Emma Davis"],
  },
]
